services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: cv-analyzer-backend-dev
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./backend/src:/app/src
      - ./backend/pom.xml:/app/pom.xml
      - ~/.m2:/root/.m2
    networks:
      - cv-analyzer-network
    command: mvn spring-boot:run

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: cv-analyzer-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://backend:8080
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
    depends_on:
      - backend
    networks:
      - cv-analyzer-network
    command: npm start

networks:
  cv-analyzer-network:
    driver: bridge
