FROM maven:3.9.6

# Set working directory
WORKDIR /app

# Copy pom.xml and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copy source code
COPY src ./src

# Expose port
EXPOSE 8080

# Run the application in development mode
CMD ["mvn", "spring-boot:run"]
